export const examData = {
  exams: [
    {
      id: "exam1",
      title: "Midterm Exam",
      course: "CS301: Database Systems",
      date: "2025-05-25",
      time: "10:00 AM",
      duration: 60,
      status: "upcoming",
      questions: [
        {
          question: "What is a primary key in a relational database?",
          options: [
            "A unique identifier for a record in a table",
            "A key that can contain null values",
            "A key that can have duplicate values",
            "A foreign key that references another table",
          ],
        },
        {
          question: "Which of the following is NOT a type of SQL join?",
          options: ["Inner Join", "Left Join", "Right Join", "Parallel Join"],
        },
        {
          question: "What does ACID stand for in database transactions?",
          options: [
            "Atomicity, Consistency, Isolation, Durability",
            "Availability, Consistency, Integrity, Durability",
            "Atomicity, Correctness, Isolation, Dependency",
            "Availability, Consistency, Isolation, Distribution",
          ],
        },
        {
          question: "Which normal form eliminates transitive dependencies?",
          options: [
            "First Normal Form (1NF)",
            "Second Normal Form (2NF)",
            "Third Normal Form (3NF)",
            "Boyce-Codd Normal Form (BCNF)",
          ],
        },
        {
          question: "What is the purpose of an index in a database?",
          options: [
            "To improve the speed of data retrieval operations",
            "To ensure data integrity",
            "To reduce the size of the database",
            "To encrypt sensitive data",
          ],
        },
      ],
    },
    {
      id: "exam2",
      title: "Final Exam",
      course: "CS201: Data Structures",
      date: "2025-05-28",
      time: "2:00 PM",
      duration: 90,
      status: "upcoming",
      questions: [],
    },
    {
      id: "exam3",
      title: "Quiz 2",
      course: "CS401: Web Development",
      date: "2025-05-30",
      time: "11:00 AM",
      duration: 30,
      status: "upcoming",
      questions: [],
    },
    {
      id: "exam4",
      title: "Midterm Exam",
      course: "CS401: Web Development",
      date: "2025-05-15",
      time: "10:00 AM",
      duration: 60,
      status: "completed",
      questions: [],
    },
    {
      id: "exam5",
      title: "Quiz 1",
      course: "CS201: Data Structures",
      date: "2025-05-10",
      time: "9:00 AM",
      duration: 30,
      status: "completed",
      questions: [],
    },
  ],
  courses: [
    {
      id: "cs101",
      code: "CS101",
      name: "Introduction to Programming",
      instructor: "Dr. Jane Smith",
      students: 42,
    },
    {
      id: "cs201",
      code: "CS201",
      name: "Data Structures",
      instructor: "Dr. John Doe",
      students: 35,
    },
    {
      id: "cs301",
      code: "CS301",
      name: "Database Systems",
      instructor: "Prof. Alice Johnson",
      students: 28,
    },
    {
      id: "cs401",
      code: "CS401",
      name: "Web Development",
      instructor: "Prof. Bob Brown",
      students: 23,
    },
  ],
  students: [
    {
      id: "s1",
      name: "John Doe",
      email: "john.doe@example.com",
      studentId: "S12345",
    },
    {
      id: "s2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      studentId: "S12346",
    },
    {
      id: "s3",
      name: "Bob Johnson",
      email: "bob.johnson@example.com",
      studentId: "S12347",
    },
  ],
}
